---
apiVersion: project.openshift.io/v1
kind: ProjectRequest
metadata:
  name: new-project
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: new-project
spec:
  hard:
    pods: "10" # Maximum number of pods
    requests.cpu: "4" # Total amount of CPU time that can be requested by pods
    requests.memory: 4Gi # Total amount of RAM that can be requested by pods
    limits.cpu: "10" # Total amount of CPU time that can be used by pods
    limits.memory: 10Gi # Total amount of RAM that can be used by pods
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: new-project
spec:
  limits:
  - type: Pod
    max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: "200m"
      memory: 100Mi
  - type: Container
    default:
      cpu: "300m"
      memory: 200Mi
    defaultRequest:
      cpu: "200m"
      memory: 100Mi
    max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: "100m"
      memory: 50Mi
