apiVersion: v1
kind: ResourceQuota  #This defines the kind of Kubernetes object you’re creating. In this case, it’s a ResourceQuota, which provides constraints that limit aggregate resource consumption per namespace.
metadata:
  name: compute-resources
spec:
  hard:
    pods: "10" # Maximum number of pods
    requests.cpu: "4" # Total amount of CPU time that can be requested by pods
    requests.memory: 4Gi # Total amount of RAM that can be requested by pods
    limits.cpu: "10" # Total amount of CPU time that can be used by pods
    limits.memory: 10Gi # Total amount of RAM that can be used by pods
