apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: example-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       example-deployment
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Auto"


# sample YAML configuration for a Vertical Pod Autoscaler (VPA) in OpenShift that scales based on either CPU or memory utilization of 80%:
